# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QFrame,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QSizePolicy, QSpinBox, QTimeEdit, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(634, 628)
        self.Button_AddLimit = QPushButton(Dialog)
        self.Button_AddLimit.setObjectName(u"Button_AddLimit")
        self.Button_AddLimit.setGeometry(QRect(410, 390, 93, 28))
        self.Button_Update_Config = QPushButton(Dialog)
        self.Button_Update_Config.setObjectName(u"Button_Update_Config")
        self.Button_Update_Config.setGeometry(QRect(410, 580, 191, 28))
        self.Button_RemoveLimit = QPushButton(Dialog)
        self.Button_RemoveLimit.setObjectName(u"Button_RemoveLimit")
        self.Button_RemoveLimit.setGeometry(QRect(510, 390, 93, 28))
        self.listWidget = QListWidget(Dialog)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(40, 440, 561, 131))
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(40, 140, 561, 16))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.LimitTimeFrame = QFrame(Dialog)
        self.LimitTimeFrame.setObjectName(u"LimitTimeFrame")
        self.LimitTimeFrame.setGeometry(QRect(20, 150, 591, 151))
        self.LimitTimeFrame.setFrameShape(QFrame.StyledPanel)
        self.LimitTimeFrame.setFrameShadow(QFrame.Raised)
        self.CB_Monday = QCheckBox(self.LimitTimeFrame)
        self.CB_Monday.setObjectName(u"CB_Monday")
        self.CB_Monday.setGeometry(QRect(20, 130, 71, 20))
        self.CB_Tuesday = QCheckBox(self.LimitTimeFrame)
        self.CB_Tuesday.setObjectName(u"CB_Tuesday")
        self.CB_Tuesday.setGeometry(QRect(100, 130, 81, 20))
        self.CB_Friday = QCheckBox(self.LimitTimeFrame)
        self.CB_Friday.setObjectName(u"CB_Friday")
        self.CB_Friday.setGeometry(QRect(360, 130, 81, 20))
        self.CB_Sunday = QCheckBox(self.LimitTimeFrame)
        self.CB_Sunday.setObjectName(u"CB_Sunday")
        self.CB_Sunday.setGeometry(QRect(510, 130, 81, 20))
        self.CB_Wednesday = QCheckBox(self.LimitTimeFrame)
        self.CB_Wednesday.setObjectName(u"CB_Wednesday")
        self.CB_Wednesday.setGeometry(QRect(180, 130, 91, 20))
        self.CB_Saturday = QCheckBox(self.LimitTimeFrame)
        self.CB_Saturday.setObjectName(u"CB_Saturday")
        self.CB_Saturday.setGeometry(QRect(430, 130, 81, 20))
        self.CB_Thursday = QCheckBox(self.LimitTimeFrame)
        self.CB_Thursday.setObjectName(u"CB_Thursday")
        self.CB_Thursday.setGeometry(QRect(280, 130, 81, 20))
        self.TimeFrameEnd = QTimeEdit(self.LimitTimeFrame)
        self.TimeFrameEnd.setObjectName(u"TimeFrameEnd")
        self.TimeFrameEnd.setGeometry(QRect(170, 30, 81, 22))
        self.SelectAllDay = QPushButton(self.LimitTimeFrame)
        self.SelectAllDay.setObjectName(u"SelectAllDay")
        self.SelectAllDay.setGeometry(QRect(300, 80, 151, 28))
        self.SelectWeekend = QPushButton(self.LimitTimeFrame)
        self.SelectWeekend.setObjectName(u"SelectWeekend")
        self.SelectWeekend.setGeometry(QRect(160, 80, 131, 28))
        self.TimeFrameBegin = QTimeEdit(self.LimitTimeFrame)
        self.TimeFrameBegin.setObjectName(u"TimeFrameBegin")
        self.TimeFrameBegin.setGeometry(QRect(60, 30, 81, 22))
        self.label_4 = QLabel(self.LimitTimeFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 30, 21, 20))
        self.label_3 = QLabel(self.LimitTimeFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 81, 20))
        self.SelectWeekday = QPushButton(self.LimitTimeFrame)
        self.SelectWeekday.setObjectName(u"SelectWeekday")
        self.SelectWeekday.setGeometry(QRect(20, 80, 131, 28))
        self.label_10 = QLabel(self.LimitTimeFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 60, 81, 20))
        self.label_5 = QLabel(self.LimitTimeFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 30, 41, 20))
        self.GameModeFrame = QFrame(Dialog)
        self.GameModeFrame.setObjectName(u"GameModeFrame")
        self.GameModeFrame.setGeometry(QRect(30, 10, 561, 131))
        self.GameModeFrame.setFrameShape(QFrame.StyledPanel)
        self.GameModeFrame.setFrameShadow(QFrame.Raised)
        self.CB_Classic = QCheckBox(self.GameModeFrame)
        self.CB_Classic.setObjectName(u"CB_Classic")
        self.CB_Classic.setGeometry(QRect(10, 10, 81, 20))
        self.CB_Aram = QCheckBox(self.GameModeFrame)
        self.CB_Aram.setObjectName(u"CB_Aram")
        self.CB_Aram.setGeometry(QRect(10, 40, 81, 20))
        self.CB_MatchedGame = QCheckBox(self.GameModeFrame)
        self.CB_MatchedGame.setObjectName(u"CB_MatchedGame")
        self.CB_MatchedGame.setGeometry(QRect(200, 10, 121, 20))
        self.label = QLabel(self.GameModeFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 100, 111, 20))
        self.CB_PracticeTool = QCheckBox(self.GameModeFrame)
        self.CB_PracticeTool.setObjectName(u"CB_PracticeTool")
        self.CB_PracticeTool.setGeometry(QRect(10, 70, 121, 20))
        self.TimeOffset = QSpinBox(self.GameModeFrame)
        self.TimeOffset.setObjectName(u"TimeOffset")
        self.TimeOffset.setGeometry(QRect(120, 100, 42, 22))
        self.CB_CustomGame = QCheckBox(self.GameModeFrame)
        self.CB_CustomGame.setObjectName(u"CB_CustomGame")
        self.CB_CustomGame.setGeometry(QRect(200, 40, 111, 20))
        self.LimitValue = QFrame(Dialog)
        self.LimitValue.setObjectName(u"LimitValue")
        self.LimitValue.setGeometry(QRect(40, 310, 281, 121))
        self.LimitValue.setFrameShape(QFrame.StyledPanel)
        self.LimitValue.setFrameShadow(QFrame.Raised)
        self.CheckingDuration = QSpinBox(self.LimitValue)
        self.CheckingDuration.setObjectName(u"CheckingDuration")
        self.CheckingDuration.setGeometry(QRect(230, 0, 42, 22))
        self.label_7 = QLabel(self.LimitValue)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 60, 201, 20))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_8 = QLabel(self.LimitValue)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(110, 30, 101, 20))
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.MinGameLength = QSpinBox(self.LimitValue)
        self.MinGameLength.setObjectName(u"MinGameLength")
        self.MinGameLength.setGeometry(QRect(230, 60, 42, 22))
        self.MaxGameCount = QSpinBox(self.LimitValue)
        self.MaxGameCount.setObjectName(u"MaxGameCount")
        self.MaxGameCount.setGeometry(QRect(230, 30, 42, 22))
        self.MaxGameLength = QSpinBox(self.LimitValue)
        self.MaxGameLength.setObjectName(u"MaxGameLength")
        self.MaxGameLength.setGeometry(QRect(230, 90, 42, 22))
        self.label_9 = QLabel(self.LimitValue)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 0, 111, 20))
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_6 = QLabel(self.LimitValue)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(-20, 90, 231, 20))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.LimitValue.raise_()
        self.GameModeFrame.raise_()
        self.LimitTimeFrame.raise_()
        self.Button_AddLimit.raise_()
        self.Button_Update_Config.raise_()
        self.Button_RemoveLimit.raise_()
        self.listWidget.raise_()
        self.line.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
#if QT_CONFIG(whatsthis)
        self.Button_AddLimit.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Add the limit into the list</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.Button_AddLimit.setText(QCoreApplication.translate("Dialog", u"Add Limit", None))
#if QT_CONFIG(whatsthis)
        self.Button_Update_Config.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Save config to file</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.Button_Update_Config.setText(QCoreApplication.translate("Dialog", u"Update saved config", None))
#if QT_CONFIG(whatsthis)
        self.Button_RemoveLimit.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Remove the selected limit from the list</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.Button_RemoveLimit.setText(QCoreApplication.translate("Dialog", u"Remove Limit", None))
        self.CB_Monday.setText(QCoreApplication.translate("Dialog", u"Monday", None))
        self.CB_Tuesday.setText(QCoreApplication.translate("Dialog", u"Tuesday", None))
        self.CB_Friday.setText(QCoreApplication.translate("Dialog", u"Friday", None))
        self.CB_Sunday.setText(QCoreApplication.translate("Dialog", u"Sunday", None))
        self.CB_Wednesday.setText(QCoreApplication.translate("Dialog", u"Wednesday", None))
        self.CB_Saturday.setText(QCoreApplication.translate("Dialog", u"Saturday", None))
        self.CB_Thursday.setText(QCoreApplication.translate("Dialog", u"Thursday", None))
        self.SelectAllDay.setText(QCoreApplication.translate("Dialog", u"Select All Days In Week", None))
        self.SelectWeekend.setText(QCoreApplication.translate("Dialog", u"Select Only Weekend", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"TO", None))
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Time in day that this limit is applicable. (Example: Only enforce limit after 6PM)</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Time Frame: ", None))
        self.SelectWeekday.setText(QCoreApplication.translate("Dialog", u"Select Only Weekday", None))
#if QT_CONFIG(whatsthis)
        self.label_10.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Day in week that this limit apply</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Day in week:", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"FROM ", None))
#if QT_CONFIG(whatsthis)
        self.CB_Classic.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Do you want to count classic Summoner's Rift games?</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.CB_Classic.setText(QCoreApplication.translate("Dialog", u"CLASSIC", None))
        self.CB_Aram.setText(QCoreApplication.translate("Dialog", u"ARAM", None))
#if QT_CONFIG(whatsthis)
        self.CB_MatchedGame.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Do you want to count normal match-making games?</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.CB_MatchedGame.setText(QCoreApplication.translate("Dialog", u"MATCHED GAME", None))
#if QT_CONFIG(whatsthis)
        self.label.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:14pt;\">Entered 6 means that any game played before 6AM of a day will be counted as the day before, useful if you don't want to reset the gaming counter after midnight</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label.setText(QCoreApplication.translate("Dialog", u"Daily Time Offset:", None))
        self.CB_PracticeTool.setText(QCoreApplication.translate("Dialog", u"PRACTICE TOOL", None))
#if QT_CONFIG(whatsthis)
        self.CB_CustomGame.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:10pt;\">Do you want to count custom games?</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.CB_CustomGame.setText(QCoreApplication.translate("Dialog", u"CUSTOM GAME", None))
#if QT_CONFIG(whatsthis)
        self.label_7.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Minimum of game time that makes you satisfied, in case you played 2 games in a row that enemy team surrender at 5 minutes.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Very Satisfying Total Game Length:", None))
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Maximum number of games allowed to play. (Game that is too short will be handled by the &quot;Very Satisfying Total Game Length&quot; box below)</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Max Game Count:", None))
#if QT_CONFIG(whatsthis)
        self.label_9.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>Time frame for the limit, game played before this time is not counted.</p><p>Example: 24 hours for daily limit, 168 hours for 7 days limit, 672 hours for 30 days limit</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Checking Duration:", None))
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("Dialog", u"<html><head/><body><p>If your total game time exceed this value, no more game. (Use in case of one long ass 70 minutes game for example)</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Maximum Total Game Length:", None))
    # retranslateUi

